const arrTracks = [
  {
    id: 0,
    trackName: "Guilt",
    TrackAuthor: "Nero",
    album: "Welcome Reality",
    isliked: false,
    trackTime: "4:44",
    genre: "Электронная музыка",
    year: 2011,
  },
  {
    id: 1,
    trackName: "Elektro",
    TrackAuthor: "Dynoro, Outwork, Mr. Gee",
    album: "Elektro",
    isliked: false,
    trackTime: "2:22",
    genre: "Электронная музыка",
    year: 2021,
  },
  {
    id: 2,
    trackName: "I’m Fire",
    TrackAuthor: "Ali Bakgor",
    album: "I’m Fire",
    isliked: false,
    trackTime: "2:22",
    genre: "Поп-музыка",
    year: 2008,
  },
  {
    id: 3,
    trackName: "Non Stop",
    remix: "Remix",
    TrackAuthor: "Стоункат, Psychopath",
    album: "Non Stop",
    isliked: false,
    trackTime: "4:12",
    genre: 'Техно',
    year: 2007,
  },
  {
    id: 4,
    trackName: "Run Run",
    remix: "feat. AR/CO",
    TrackAuthor: "Jaded, Will Clarke, AR/CO",
    album: "Run Run",
    isliked: false,
    trackTime: "2:54",
    genre: 'Хип-хоп',
    year: 2010,    
  },
  {
    id: 5,
    trackName: "Eyes on Fire",
    remix: "Zeds Dead Remix",
    TrackAuthor: "Blue Foundation, Zeds Dead",
    album: "Eyes on Fire",
    isliked: false,
    trackTime: "5:20",
    genre: 'Рок',
    year: 2007,
  },
  {
    id: 6,
    trackName: "Mucho Bien",
    remix: "Hi Profile Remix",
    TrackAuthor: "HYBIT, Mr. Black, Offer Nissim, Hi Profile",
    album: "Mucho Bien",
    isliked: false,
    trackTime: "3:41",
    genre: 'Поп-музыка',
    year: 2022,
  },
  {
    id: 7,
    trackName: "Knives n Cherries",
    TrackAuthor: "minthaze",
    album: "Captivating",
    isliked: false,
    trackTime: "1:48",
    genre: 'Хип-хоп',
    year: 2022,
  },
  {
    id: 8,
    trackName: "Halfway to Hell",
    TrackAuthor: "Jelly Roll",
    album: "Whitsitt Chapel",
    isliked: false,
    trackTime: "2:58",
    genre: 'Кантри',
    year: 2023,
  },
];
export default arrTracks;
